### ISSUE TITLE
Les deux sites XMLTV ne fonctionnent plus !

### ISSUE THREAD

**Issue by vmagnin** [vmagnin/pyxmltv#2]
A ce jour :
- http://myxmltv.lescigales.org/xmltv.zip => fichier vide
- http://www.xmltv.fr/guide/tvguide.zip => "Site non installé"

Il faudrait trouver d'autres sites.

**Comment by vmagnin** [comment]
La solution semble se trouver en Suisse :
- https://www.windowsmediacenter.fr/2020/02/16/xmltv-france-a-ferme-xmltv-suisse-permet-desormais-de-telecharger-le-guide-tv-de-la-tnt-francaise/
- https://xmltv.ch/
- http://xmltv.ch/xmltv/xmltv-tnt.xml

J'essaierai d'utiliser ce fichier XML.

**Comment by vmagnin** [comment]
Ca marche.

**Comment by 3710-sudo** [comment]
le XMLTV suisse ne semble pas complet, je n'ai que 1 ou 2 jours d'EPG...avez-vous une solution ?

**Comment by vmagnin** [comment]
> le XMLTV suisse ne semble pas complet, je n'ai que 1 ou 2 jours d'EPG...avez-vous une solution ?

De mon côté, le fichier `xmltv-tnt.xml` d'aujourd'hui va jusqu'au 1er mars, donc 6 jours de contenu. Vérifiez la taille de votre fichier : ~ 3,2 Mio. Si vous l'ouvrez dans un éditeur de texte, quelles sont les dernières dates à la fin ?

**Comment by 3710-sudo** [comment]
merci je devais avoir un soucis de mise à jour, maintenant j'ai bien les programmes jusqu'au 01/03

**Comment by vmagnin** [comment]
Voir également https://github.com/vmagnin/pyxmltv/issues/3
On peut avoir 12 jours de programme (mais je n'ai pas testé récemment).
